name: TestAction Workflow
on:
  push:
    branches: [master]
jobs:
  GenerateBuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          node-version: 14.x
      - name: Create Folder
        run: mkdir Build_Files 
      - name: Clone Files  
        run: git clone https://github.com/aslambaba/MyShoes.git
        working-directory: ./Build_Files
      - name: GitBranch Status
        run: git checkout build-files && rm -r * && git checkout master *
        working-directory: ./Build_Files/MyShoes/
      - name: Remove GitIgnore File
        run: |
          rm .gitignore
          git config --global user.name github_workflow
          git config --global user.email aslam91r@gmail.com
          git remote set-url origin https://${{secrets.ACC_GIT}}@github.com/aslambaba/MyShoes.git
          git commit -am 'Remove GitIgnore File'
        working-directory: ./Build_Files/MyShoes/
      - name: Install Dep
        run: npm install
        working-directory: ./Build_Files/MyShoes/
      - name: Build Project
        run: npm run build
        working-directory: ./Build_Files/MyShoes/
      - name: Remove NodeModule
        run: rm -r node_modules/
        working-directory: ./Build_Files/MyShoes/
      - name: Deploy Project on Build Branch
        run: |
          git config --global user.name github_workflow
          git config --global user.email aslam91r@gmail.com
          git remote set-url origin https://${{secrets.ACC_GIT}}@github.com/aslambaba/MyShoes.git
          git add .
          git commit -m 'Add Build Image'
        working-directory: ./Build_Files/MyShoes/
      - name: Check files on build branch
        run: git branch && ls -a
        working-directory: ./Build_Files/MyShoes/
      - name: Push to Build Branch
        run: git push origin build-files
        working-directory: ./Build_Files/MyShoes/